language: go

go:
  - 1.13.x
  - 1.14.x

before_install:
  - go get -t -v ./...

script:
  - go test -v ./... --tags integration -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
